spring.application.name=server

# --- H2 & JPA for dev ---
spring.h2.console.enabled=true

# Common JPA/diagnostics (apply to all profiles)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

# Error text in dev/PRs
server.error.include-message=always
server.error.include-binding-errors=always