# --- H2 & JPA for dev ---
spring.h2.console.enabled=true

# In-memory DB (fresh each run). H2 console at /h2-console
spring.datasource.url=jdbc:h2:mem:chess;DB_CLOSE_DELAY=-1
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update